import numpy as np
import matplotlib.pyplot as plt
from pipe import Pipe

class Node:

    def __init__(self, x, y, z, node_id):

        self.pipes_in = {}
        self.pipes_out = {}
        
        self.x = x
        self.y = y
        self.z = z  
        self.node_id = node_id 

        """
        TODO: Working with T and flow requires using a timestep. This can be later implemented when implementing the for loop simulation. 
        """
        

    def initialize_node(self, num_steps, T_init) -> None:
        """
        Initialize the temperature in the node

        Args:
        num_steps: number of steps the simulation takes
        T_init: initial temperature [K]
        """

        self.T = np.zeros(num_steps)
        self.T[0] = T_init


    def add_pipe(self, pipe_id, pipe, direction):
        """
        Function that adds an pipe to the node.

        Args:
            pipe_id : id of the pipe
            pipe (Pipe): the pipe to be added to the node.
            direction (str): the direction of the pipe, either 'in' or 'out'.
        """

        if direction == 'incoming':
            self.pipes_in[pipe_id] = pipe
        elif direction == 'outgoing':
            self.pipes_out[pipe_id] = pipe
        else:
            raise ValueError(f"Invalid direction: {direction}")
        
    def set_T(self, N):
        """
        Function that calculates the flow of each in- and output pipe of the node. And sets the node temperature

        For now divide the mass flow based on the diameter of the pipes. 

        # TODO: maybe it need to put in the new flow at N + 1
        """         
        # print(f'temperature node {self.T[N]}')

        if N == 100 and self.node_id == 'Node 5': # debug
            pass 

        sum_T_flow = 0
        sum_m_inflow = 0
        for _, pipe in self.pipes_in.items():
            
            m_inflow = pipe.get_m_flow(N)
            sum_T_flow += pipe.T[N] * m_inflow
            sum_m_inflow += m_inflow
        try:    
            self.T[N] = sum_T_flow / sum_m_inflow # set the node temperature

            # Set temperature per pipe
            for _, pipe in self.pipes_out.items():
                pipe.set_T_in(self.T[N], N)

        except(ZeroDivisionError):
            print(f"No ingoing mass flow in node  = {self.node_id}")
            

    def set_m_flow(self, N):
        """
        Function that calculates the flow of each in- and output pipe of the node. And sets the node temperature

        For now divide the mass flow based on the diameter of the pipes. 

        # TODO: put in a ratio for the mass flow, to decide how it will be divided. 
        """         

        sum_m_flow = 0
        for _, pipe in self.pipes_in.items():
            
            m_inflow = pipe.get_m_flow(N)
            sum_m_flow += m_inflow
        
        try:    
            # Set the node mass outflow and temperature per pipe
            m_pipe_flow = sum_m_flow / len(self.pipes_out)
            for pipe_id, pipe in self.pipes_out.items():
                pipe.set_m_flow_m(m_pipe_flow, N)

                # print(f'{pipe_id}, flow : {m_pipe_flow}') # debug

        except(ZeroDivisionError):
            print(f"No ingoing mass flow in node  = {self.node_id}")

    #     # TODO: workout the pressure calculation to further give this meaning. 



    def get_T(self, N):
        return self.T[N]

    def get_number_pipes_in(self):
        return len(self.pipes_in)

    def get_number_pipes_out(self):
        return len(self.pipes_out)


# NOTE: Generated by Github Copilot, not sure whether I would use it
    # def remove_pipe(self,pipe):
    #     """
    #     Function that removes an pipe from the node.

    #     Args:
    #         pipe (Pipe): the pipe to be removed from the node.
    #     """

    #     if pipe in self.pipes_in:
    #         self.pipes_in.remove(pipe)
    #     elif pipe in self.pipes_out:
    #         self.pipes_out.remove(pipe)
    #     else:
    #         raise ValueError(f"Pipe {pipe} not found in node")



if __name__ == "__main__":

    node1 = Node(1,1,1, 'Node 1')
    pipe1 = Pipe(10, 0.1, 0.08, 100, 'Pipe 1')
    node1.add_pipe('pipe1', pipe1, 'outgoing')
    
    node1.set_m_flow(0)
    node1.set_T(0)

    print(node1.get_number_pipes_out())